### ISSUE TITLE
Failed to build with latest tonic v0.8.0

### ISSUE THREAD

**Issue by arronwy** [confidential-containers/guest-components#260]
```
   Compiling tonic v0.8.0
error[E0277]: the trait bound `utils::keyprovider::KeyProviderKeyWrapProtocolInput: prost::message::Message` is not satisfied
   --> src/utils/keyprovider.rs:100:60
    |
100 |             self.inner.unary(request.into_request(), path, codec).await
    |                        -----                               ^^^^^ the trait `prost::message::Message` is not implemented for `utils::keyprovider::KeyProviderKeyWrapProtocolInput`
    |                        |
    |                        required by a bound introduced by this call
    |
    = note: required because of the requirements on the impl of `Codec` for `ProstCodec<utils::keyprovider::KeyProviderKeyWrapProtocolInput, _>`
note: required by a bound in `tonic::client::Grpc::<T>::unary`
   --> /home/arron/.cargo/registry/src/github.com-1ecc6299db9ec823/tonic-0.8.0/src/client/grpc.rs:149:12
    |
149 |         C: Codec<Encode = M1, Decode = M2>,
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ required by this bound in `tonic::client::Grpc::<T>::unary`

error[E0277]: the trait bound `utils::keyprovider::KeyProviderKeyWrapProtocolOutput: prost::message::Message` is not satisfied

```
The build with works with:
```
tonic = { version = "0.7.2", optional = true }
```
@pravinrajr9 Could you help to fix this issue?
